version: "3.8"

services:
  app:
    image: search-engine-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: search_engine_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Password123
    ports:
      - "8080:8080"
    networks:
      - app_network
    command: /bin/sh -c "sleep 60 && java -jar app.jar"

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_DATABASE: search_engine
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 20s
      retries: 10
      start_period: 20s

volumes:
  db_data:

networks:
  app_network:
